# Generated by Django 4.1.13 on 2024-06-04 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.carousel_image_path)),
                ('alt', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=256, null=True)),
                ('index_text', models.TextField(blank=True, default='')),
                ('about_title', models.CharField(blank=True, default='About Me', max_length=256)),
                ('about_text', models.TextField(default='')),
                ('about_picture', models.ImageField(blank=True, upload_to=portfolio.models.about_picture_path)),
                ('about_picture_alt', models.CharField(blank=True, default='', max_length=256)),
                ('portfolio_title', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=256, null=True)),
                ('whatsapp_link', models.URLField(blank=True, max_length=256, null=True)),
                ('github_link', models.URLField(blank=True, max_length=256, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Website Info',
                'verbose_name_plural': 'Website Info',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('github_link', models.URLField(blank=True, max_length=128, null=True)),
                ('display_online', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(blank=True, to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=portfolio.models.project_image_path)),
                ('alt', models.CharField(blank=True, default='', max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.projects')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Image',
            },
        ),
    ]
