# Generated by Django 4.1.13 on 2024-05-09 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('github_link', models.URLField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(to='portfolio.category')),
            ],
        ),
    ]
