# Generated by Django 4.1.13 on 2024-05-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='descriptions',
        ),
    ]
