# Generated by Django 4.1.13 on 2024-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='date',
            new_name='publish_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='develop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
