# Generated by Django 4.1.13 on 2024-05-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_description_projects_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='descriptions',
            new_name='description',
        ),
    ]
