# Generated by Django 4.1.13 on 2024-05-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_category_projects_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
    ]
