# Generated by Django 4.1.13 on 2024-05-17 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
