# Generated by Django 4.1.13 on 2024-05-18 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_about_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(max_length=256)),
                ('github_link', models.URLField(max_length=256)),
                ('linkedin_link', models.URLField(max_length=256)),
                ('email', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
