# Generated by Django 4.1.13 on 2024-05-21 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_projects_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=256, null=True)),
                ('index_text', models.TextField(blank=True, default='')),
                ('about_title', models.CharField(blank=True, default='About Me', max_length=256)),
                ('about_text', models.TextField(default='')),
                ('about_picture', models.ImageField(blank=True, upload_to='images/about/%Y/%m/%d')),
                ('whatsapp_link', models.URLField(blank=True, max_length=256, null=True)),
                ('github_link', models.URLField(blank=True, max_length=256, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Website Info',
                'verbose_name_plural': 'Website Info',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Image'},
        ),
    ]
