# Generated by Django 4.1.13 on 2024-05-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_websiteinfo_delete_about_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='display_online',
            field=models.BooleanField(default=True),
        ),
    ]
