# Generated by Django 4.1.13 on 2024-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
