# Generated by Django 4.1.13 on 2024-05-27 18:19

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_category_slug_alter_projects_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.project_image_path),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='about_picture',
            field=models.ImageField(blank=True, upload_to=portfolio.models.about_picture_path),
        ),
    ]
