# Generated by Django 4.1.13 on 2024-05-27 18:36

from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_projectimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.carousel_image_path)),
                ('alt', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
            },
        ),
    ]
