# Generated by Django 4.1.13 on 2024-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_carouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='about_picture_alt',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
