# Generated by Django 4.1.13 on 2024-05-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_projectimage_alt_websiteinfo_about_picture_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='contact_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
