# Generated by Django 4.1.13 on 2024-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_projects_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.ManyToManyField(blank=True, to='portfolio.category'),
        ),
    ]
